Workaround to install webassets==0.12.1
Using the more modern pip version gave the following error, so we first
install webassets and then we upgrade pip

  File "/usr/lib/python3.9/site-packages/pip/_internal/utils/unpacking.py", line 235, in untar_file
    tar.extractall(location, filter=pip_filter)
  File "/usr/lib/python3.9/tarfile.py", line 2250, in extractall
    self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/usr/lib/python3.9/tarfile.py", line 2313, in _extract_one
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/lib/python3.9/tarfile.py", line 2404, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "/usr/lib/python3.9/tarfile.py", line 2501, in makelink
    self._extract_member(self._find_link_target(tarinfo),
  File "/usr/lib/python3.9/tarfile.py", line 2705, in _find_link_target
    raise KeyError("linkname %r not found" % linkname)
KeyError: "linkname 'webassets-0.12.1/examples/appengine/webassets/__init__.py' not found"