Remove gevent system packages
It's not clear we are using this, and they were installing a system-wide
packaging package that could not be uninstalled when installing CKAN
requirements:

error: uninstall-distutils-installed-package

Cannot uninstall packaging 21.3
╰─> It is a distutils installed project and thus we cannot accurately...